---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security-auth
  namespace: default
spec:
  chain:
    middlewares:
      - name: default-ak-outpost-traefik@kubernetescrd
