---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authentik
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 2022.5.1
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2022.6.1

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN}"
        traefik.ingress.kubernetes.io/router.middlewares: "traefik-system-cloudflare-only@kubernetescrd"
        external-dns/is-public: "true"
      hosts:
        - host: &host auth.${SECRET_DOMAIN}
          paths:
            - path: /
      tls:
        - secretName: auth-cert
          hosts:
            - "auth.${SECRET_DOMAIN}"

    additionalContainers:
      - name: broker
        image: redis:7.0
        imagePullPolicy: IfNotPresent


    geoip:
      enabled: true

    envFrom:
      - secretRef:
          name: *app

    authentik:
      log_level: debug
      outposts:
        docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s

    postgresql:
      enabled: true
    redis:
      enabled: true

  valuesFrom:
    - kind: Secret
      name: authentik
      valuesKey: AUTHENTIK_GEOIP_ACCOUNT_ID
      targetPath: geoip.accountId
      optional: false
    - kind: Secret
      name: authentik
      valuesKey: AUTHENTIK_GEOIP_LICENSE_KEY
      targetPath: geoip.licenseKey
      optional: false
