apiVersion: v1
kind: Secret
metadata:
    name: authentik
    namespace: default
stringData:
    AUTHENTIK_GEOIP_ACCOUNT_ID: ENC[AES256_GCM,data:I+pegudY,iv:L21GHH4k8suY03Bky42SVFBpSjqwe7Id74imeAmPe9U=,tag:dtpPob90Wgtsvy+hK5hd0g==,type:str]
    AUTHENTIK_GEOIP_LICENSE_KEY: ENC[AES256_GCM,data:APSFW2ujxLEAxQsxf/dniQ==,iv:WPJKYUyhyr5PjKPxNX7Ode2fT9mrrtQ+w//tP3jNzUc=,tag:we0BfCjD6I8LT0N2Ml7r3g==,type:str]
    postgres-password: ENC[AES256_GCM,data:cICEENPaXIgiYQe6cDKP0LD9wAuNwFGmBpdK8A==,iv:dDC4Pgjzx+YNsqt9sUm89R3HX09JOewuBhNs6B/l7Kw=,tag:EkRpBHZjX7XVZ2eUVx+lZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13pchl42neheadfr9vun5h7ky7sdxvg2xywgkxz2vvzwh56fdvuds65e0q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvT2ZkUjNKM21MVXhSUnV4
            THk2bXZVbDhpYlA4bTQwMEdzaWhERUpUeERrCnRxT1NuQ25Hd3VRL0QrNUF6MVdt
            SXExRVFkakhEV011Q1FpMHVxVUxKVFkKLS0tIG9BTDQzc1Nna0wwSWdXUTNEZTZ6
            KzdRMExjVjkwaTBIQnR1Uklvd1RtTlkK28ZHaWdf5XgRbSQvxN6rcTYLGyVj1AwQ
            YL8nZz49yyLetlNsysqwtTWZxJpBaXOCbiMNqADu6qljInyUi0mIWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-05T16:48:44Z"
    mac: ENC[AES256_GCM,data:31LywFWqJWYVdSIxHQZIM0sEYo6POzBE+zZhrpf/mEu91KzTJrvZH6S5NpCb0NgklGqvedr9AHobTcLip3jOBUbgktTnpuJjP6JruzlgmurmSGiww0F8014JqKiBSXk9yzkFBRYhLQCDM36TVRsz3xUleD65sIvKJMw1lrXCA5U=,iv:b4HMAMX9pmFQUEf+Bog2TPd9UNXM2JrI7J8uFzVhVOI=,tag:NCuKKV4/OP5NrPgSQApQ5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
