---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config-v2
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
