apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: esphome
      version: 8.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: esphome/esphome
      tag: 2022.4.0
      pullPolicy: IfNotPresent
    env:
      TZ: "${TIMEZONE}"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-local-only-access@kubernetescrd"
        hosts:
          - host: "esphome.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "esphome.${SECRET_DOMAIN}"
            secretName: "esphome-tls"
    persistence:
      config:
        enabled: true
        existingClaim: esphome-config-v1
