apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: home-automation
stringData:
    postgres-password: ENC[AES256_GCM,data:ghRaAdgrrhHTJBD0IBZQD6YqZGP8Q8EXbUw=,iv:a1onxOnbQ63IN2gB2HTc4sn2sZR8dZoLhZAGflI1bYA=,tag:PdPmfhZxmQFUV5fNVCWsKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13pchl42neheadfr9vun5h7ky7sdxvg2xywgkxz2vvzwh56fdvuds65e0q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTlhRQkdJYnV0M0pQOHJu
            STluVTg0aDZObVFBTEpEV3Z0QlBMdHVqUDNBCkVNYnNCL2FFRWZEdmYxTVdkd2ha
            TElrN05nS2VMQlpjNzJQK2RKeTlMRmsKLS0tIFpSb0FFcWxBQ3BuZlJKNndqVGlo
            R2JkOGhLL3NiSHkrT0x0SXhTUEhzWU0KIf8UFMtqpfRIsnaE5hiZoOwLlA9JOU/G
            FeKUIj6OzzyzMRgjuw+uXJWbO9l0pJO5mzWY2rMR8QNssHBKLBcUtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-23T08:10:11Z"
    mac: ENC[AES256_GCM,data:rFvtHccWG/2cesR0Ig1jzCwBPkVPSjRcwI7zeji2p8ImxMS5dUn8d/Sg2WZNr9GoqcZIVlFmG/heOcRU3PsOT2NPu6WmN4PBpTSFbscGP3rYUTfjM4ISTZl7k4sAl7QKkCdTuphmkBVYyIku+sHbzIXWBnWfoTrIFinXZ7MtXLY=,iv:WR1rORU2CmGqUnGWpGVx1R/+wT0YPa+CRcxv7cYibcg=,tag:EXERhH2guMd15SGv+/Qztg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
