apiVersion: v1
kind: Secret
metadata:
    name: dsmr-reader
    namespace: home-automation
stringData:
    dsmr_reader_admin_user: ENC[AES256_GCM,data:I5nkXWMZ,iv:Dpa3jP9x6rfQr9/UG4uWL8IfgWRFfs2VrWYh58onVxc=,tag:VD9+IhOm8DzURcTVs+dLWg==,type:str]
    dsmr_reader_admin_password: ENC[AES256_GCM,data:N121DGFjGWV3PZra3V3/4M7kJW7Y9KlaJP0IxLk=,iv:ZMk2mVgm0xVX64ruOXhLchZMieZsCwx/aFdL9rAdkbs=,tag:X/EAh0BZxSkkj8O1R9/ILQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:cPE/1FI2GqpcWry9qeJu3HCPNvSy5EBRWLI=,iv:rmHvY6Hhn1/L68NSA78BsLxUDeEvxQmADQuImYSusGo=,tag:qjOk9pST7ZjbbiUOzujKOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13pchl42neheadfr9vun5h7ky7sdxvg2xywgkxz2vvzwh56fdvuds65e0q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWW0zR1BRMWMwYW5rY0RD
            RmRSUmhubjRwTjBYRGx0Yk1JNjVsL05XeXdNCllTcDZiWWFTaVBxait3cVhHQXFI
            Mzc0VHVaR25JVXBQais1RUEvd1RTUWcKLS0tIEZxRVI5bExoZ3RrQ2FlbnV2TG9r
            MlBHNUcrbmdIWHZRMkd3TmJSeWtpZWMK6ZFWZr83w7sZ6KAL1HCzP+DccWXxGIQF
            XBe6ApeHBTahw4CP+6qLPuqwmI1WNotvzER28SmMXhWRYRCAM32icA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-23T19:02:15Z"
    mac: ENC[AES256_GCM,data:KqvFt4LxFcqdlMfGUs6NDZCdJZC15Ikz5AT+JM3rGlIGf9rZIh0ZyzisOgNdVCJ/g5INTuPgKqduNiaPwMXvGCVzaPCNVVD0JPS12nk/H7WlwvPrvwOKy9u/S0g/lUNAxlP3OmW3HYvYVvAhxyIYubnYiIuer20EgjXhMSYtHsI=,iv:HsxgL+6bLslcfDemCh1AJ7RBx8Z1MG/JzY9kV8va1Lc=,tag:+cRtpt7rCdntiI2lIFgQaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
