apiVersion: v1
kind: Secret
metadata:
    name: dsmr-reader
    namespace: home-automation
stringData:
    DSMRREADER_ADMIN_USER: ENC[AES256_GCM,data:tV8pzmXf,iv:pBRUY0nyNT/J0ZGGPY5dYxINznFePiS9yCpqmCC6Lrc=,tag:C28LVi7DikUz+wnPSEG+4g==,type:str]
    DSMRREADER_ADMIN_PASSWORD: ENC[AES256_GCM,data:aa0uRy3t/NnFt057quqTZzQn476DfGu3IydePD4=,iv:+ttdstBeeihRyDRia3EIH7ThodvbPEeO54t49zVBUAs=,tag:p6AsqLs0EomJ4OYrCPLRjQ==,type:str]
    DJANGO_DATABASE_PASSWORD: ENC[AES256_GCM,data:171ob9gI5K8Ef4bhCoXB4mQEYfwGhgJCeV0=,iv:wM8tXH5EGdWDDvEQF8sNYvNnbSfQviY6mLSsm7o/gs0=,tag:x0fphnKuSwpC/ICq2LQG8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13pchl42neheadfr9vun5h7ky7sdxvg2xywgkxz2vvzwh56fdvuds65e0q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z2cyRUl3eDdJc0Z4ZnhD
            RnJqWkhGZFBKazVMaEVvSmlaZFZ5cE1Ma2hVCllLOG1aeE00V0tacnU4OEE0Uzdn
            UzVpNzYyN3BkQThsWVR1eXg0RXROdnMKLS0tIHBRVHpEMUV2RFJpTG5hR1creWZv
            b015L1JIZHV4aVdkVWVTRjh4K1ZYNVEKfixhtZj87yOvVWXuTqYYO3L4qgdd8JyU
            xxhmvxxXYhYzHyEOMCqWVg7K3qL8p8aUPcAXKBs0baRNO/0KpzgbYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-23T14:59:20Z"
    mac: ENC[AES256_GCM,data:uok6bHJX9s/wPXZRabe+TgKWh6O6j0OdtBDTBRFLk/MztPiIk+Vu86KcyT2psM3ry3Ir3USsVvzTWKXeA86u82v404Ex1gyvQScsx285I1uf+oRY7JKbUREFPg7grvzXJfh3Ir9nZn0bJB2Uf1BMaw9vY4Q1/w4UL1mh98292pg=,iv:gd59HAjWxznefpCf3Ra4M2c00C8Hv4FkD4eHFL/hmNk=,tag:moDVDkMo1ZbmTqJVCg4j5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
