---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik-db
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 11.6.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    auth:
      database: authentik
      existingSecret: authentik

    primary:
      persistence:
        enabled: true
        existingClaim: authentik-data

      resources:
        requests:
          cpu: 25m
          memory: 100M
        limits:
          memory: 500M
  valuesFrom:
    - kind: Secret
      name: authentik
      valuesKey: AUTHENTIK_POSTGRESQL__PASSWORD
      targetPath: global.postgresql.auth.postgresPassword
      optional: false
