---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2022.7.3
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  values:
    outposts:
      docker_image_base: ghcr.io/goauthentik/%(type)s
    fullnameOverride: authentik
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2022.7.2
      pullPolicy: Always

    authentik:
      secret_key: "${SECRET_AUTHENTIK_SECRET_KEY}"
      error_reporting:
        enabled: false
      postgresql:
        host: "authentik-postgresql"
        name: "authentik"
        user: "authentik"
        password: "${SECRET_AUTHENTIK_POSTGRES_PASSWORD}"
      redis:
        host: "authentik-redis-master"
      email:
        host: "smtp.gmail.com"
        port: 587
        use_tls: true
        username: "${SECRET_ALERT_MAIL}"
        password: "${SECRET_ALERT_MAIL_PASSWORD}"
        from: "auth@${SECRET_DOMAIN}"

    prometheus:
      serviceMonitor:
        create: true
      rules:
        create: true

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "lock"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hosts:
        - host: &host auth.${SECRET_DOMAIN}
          paths:
            - path: /
      tls:
        - secretName: auth-cert
          hosts:
            - "auth.${SECRET_DOMAIN}"

    geoip:
      enabled: true

    postgresql:
      enabled: true
      postgresqlPassword: "${SECRET_AUTHENTIK_POSTGRES_PASSWORD}"
    redis:
      enabled: true

  valuesFrom:
    - kind: Secret
      name: authentik
      valuesKey: AUTHENTIK_GEOIP_ACCOUNT_ID
      targetPath: geoip.accountId
      optional: false
    - kind: Secret
      name: authentik
      valuesKey: AUTHENTIK_GEOIP_LICENSE_KEY
      targetPath: geoip.licenseKey
      optional: false
