apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: overseerr
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/k8s-at-home/overseerr
      tag: 1.29.1
      pullPolicy: IfNotPresent
    env:
      TZ: "${TIMEZONE}"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
#          traefik.ingress.kubernetes.io/router.middlewares: "networking-local-only-access@kubernetescrd"
        hosts:
          - host: "overseerr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "overseerr.${SECRET_DOMAIN}"
            secretName: "overseerr-tls"
    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config-v1
