---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rss-to-telegram-config-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
