---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app rss-to-telegram
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    global:
      nameOverride: *app
    image:
      repository: docker.io/bokker/rss.to.telegram
      tag: "2.0.3"
    env:
      TZ: "${TIMEZONE}"
      DELAY: "60"
      DEBUG: "true"
    envFrom:
      - secretRef:
          name: *app
    persistence:
      config:
        enabled: true
        existingClaim: rss-to-telegram-config-v2
        mountPath: /app/config
    service:
      main:
        enabled: false
    ingress:
      main:
        enabled: false
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
