apiVersion: v1
kind: Secret
metadata:
    name: rss-to-telegram
    namespace: default
stringData:
    TOKEN: ENC[AES256_GCM,data:LtrGi4rtH/EKwWBxBw1rpOAmUp5BqB08NaOQzju+IlD2rz66KD2UCCGelpTxUw==,iv:/CJqr6zXhueDbmFfFvQAawBUm291hN2eHpZsFBlDOQY=,tag:IkV/5qoftqr90JMJE8Bqsw==,type:str]
    CHATID: ENC[AES256_GCM,data:5c9eojnYt1/J,iv:APjYdYmyNluFPT8syCTu7wGymwDNQjxhpuq+6ACPoyc=,tag:9gbI4w3cvhNIl1nCSoT60w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13pchl42neheadfr9vun5h7ky7sdxvg2xywgkxz2vvzwh56fdvuds65e0q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVFJQbGFveHYvZzlVR1B3
            RXgvRnIxZkkzYys2d3R4MWl0SFV5Smh0UVZvCmJ5aHM3UEFxWS9paDlPUkhnTi9t
            WW8vVGVlZjJFRjlaMFVsNUhDQTFYb3cKLS0tIFhxNGRHTDFTRWNLL2NzYlVQNFAx
            NG93YndYSFlOSFY0NytiTVlwKzZBS2sKhBhnhfcFgwAUaVJJC4uhkN3tbEzx6fXC
            8BT7HATbhZTgntZZpTuP6yhKJuMyS9Zd5MOIjl+EySY35bU8w0/4Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-16T20:02:33Z"
    mac: ENC[AES256_GCM,data:ea9bDW0AU/ooWzuBN9agP9B+nlnMXfDAXUGLs3TxYlzRHJSFrgfi3cz1ZbCs0JoPeUx/S1Emb7CX+2J2P5wIgJp+YfbdSw2ONadICIpKajLodYQaTOfg5+65V+SvYqngcPIHTAb2gkjls1PiAlMDcBp1bStDCet9Bc2icnm4Mw8=,iv:jAnrtk2TeF8rzVN6AqunH4bzNa2vsHtRkW/a1MDLUv0=,tag:AwBOYrlPia2VMVNEiHqhMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
