---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghostfolio-db
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 11.6.13
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    auth:
      database: ghostfolio
      existingSecret: ghostfolio

    primary:
      persistence:
        enabled: true
        existingClaim: ghostfolio-data-1

      resources:
        requests:
          cpu: 25m
          memory: 100M
        limits:
          memory: 500M
  valuesFrom:
    - kind: Secret
      name: ghostfolio
      valuesKey: postgres-password
      targetPath: global.postgresql.auth.postgresPassword
      optional: false
