---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghostfolio-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
