---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app ghostfolio
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
  values:
    global:
      nameOverride: *app
    image:
      repository: ghostfolio/ghostfolio
      tag: 1.173.0
    env:
      TZ: "${TIMEZONE}"
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        ports:
          http:
            port: 3333

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "bank"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-external-auth@kubernetescrd"
        hosts:
          - host: "ghostfolio.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: ghostfolio-cert
            hosts:
              - "ghostfolio.${SECRET_DOMAIN}"

    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 500Mi

    podAnnotations:
      secret.reloader.stakater.com/reload: *app

    additionalContainers:
      - name: broker
        image: redis:7.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 11m
            memory: 32M
          limits:
            memory: 32M
