---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghostfolio-mysql
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mysql
      version: 9.1.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: bitnami/mysql
      tag: 8.0.29
    architecture: standalone
    primary:
      persistence:
        existingClaim: ghostfolio-mysql-data
    auth:
      rootPassword: "${SECRET_GHOSTFOLIO_MYSQL_PASSWORD}"
      database: ghostfolio
      username: ghostfolio
      password: "${SECRET_GHOSTFOLIO_MYSQL_PASSWORD}"
      replicationPassword: "${SECRET_GHOSTFOLIO_MYSQL_PASSWORD}"
