---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql-ghostfolio
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  values:
    auth:
      database: ghostfolio
      existingSecret: ghostfolio


    primary:
      persistence:
        existingClaim: ghostfolio-db

      resources:
        requests:
          cpu: 23m
          memory: 145M
        limits:
          memory: 290M
