apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio
    namespace: default
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:hm3aj4PU9nHlFu7rDzcxbPa1o9AJuGKklR5+3CzdB5bqLzQ+xPCb+iVOmaWXjOhakm1gJ2tNUHbfrpJaN58nlTXoV9kIs/cGAWfGI+NnblzabiVEHRaIcHJqjKFbH253KWYuEVNj+EY=,iv:YjJ2VP3Xs75qwIujLROo2Drbhz/ybHCrrbKpXG93crk=,tag:6CTzpkw3UJ61fMWsaUuj+w==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:DvGy301BVykg,iv:tileZwm84aMcPrJkoFjFU2qjIejJOQ0+YFmdHcjmMM8=,tag:V4U+6orObgyjsv89MhGLZQ==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:KgFisg==,iv:6bzvt3MqfBdmK7s/4xoFrXWkwDZR6lp/GcbkFexf97E=,tag:TeLgS3zpr4TN/puxo52eHg==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:xJitrAcgADvSsIBxLA==,iv:mcDcJpf0C+36E1NkmQSrM4nV2tIBUl5tZXr6/MDIgUQ=,tag:pVQCsquCtd5B8HwX1N8FTA==,type:str]
    COMPOSE_PROJECT_NAME: ENC[AES256_GCM,data:52RE9YW4eiMiYi7+hgZKcjKWlSwncBvJo2WwI7fU0xfwwF1vTaIe8T9bmnB9VCiXWuv/0xQD4jPc3fo=,iv:SESX08WiU/NC6nfh3k3cHgoGWrwxmHQfkXQwFhAFnS8=,tag:qAw7dZy5aZi9/wF4u6kN8w==,type:str]
    PORT: ENC[AES256_GCM,data:XudcHw==,iv:8/pZ2k699H4gD2kaLbxrgDT2ppbaczj0LAYD7FVCDQ0=,tag:DootPnsDDGfYe/kq3T21OQ==,type:str]
    ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:2ReQniQ468RhL97imuAT,iv:KDZgBuhxZfwo28DAqfXB4yruy+krMdO3avZDGm2UxhA=,tag:MDxoI7ReMmzmQHhvJHhtdw==,type:str]
    postgres-password: ENC[AES256_GCM,data:PaHfomHP2nljhkrJNtYkFOSwljM4YFGy,iv:K3OOjBacqBAhm+pC8LnDrpxnxhxMalctXzC1vk5AqMI=,tag:3rKIORFzgudnIvL6eOpevg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13pchl42neheadfr9vun5h7ky7sdxvg2xywgkxz2vvzwh56fdvuds65e0q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWXVYYmI3RDJ6MDBpR1RN
            NE51dTdUTXJjbExWZitZWXJnSmdNZTUreXprCjJiWnBad05yWktwODhOcGw1eElC
            RktJa0pvc3NINVhYQmUvRDR0ZGtFWlkKLS0tIFdEWm5jejJFUTc1ZDFFcFFmTWg4
            N2xoOUVDR2dqVFFMQkh6NGlUaTlMZ00K81ojLGCHF7xa6DsjkIIntrZu20oGaJtR
            /DXeLfn87RZ81Ier3CWA/lsMDy1xktptMRlQETvIe+VJ7ArVi7GTSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-02T17:18:30Z"
    mac: ENC[AES256_GCM,data:yl5pJvsou72/IZ8pO+30Uw9XeHtq2Bg14IHbHv3+RlXdR8xoEIJ+co0ig3pemhKDOVVfCf6OiVz8DbSuGuo2a/N7cNVWh0MMFaJjOG9umkhKKa4xp8R7EXtgUCgHcaKUuL3xiN87YMEsXZJtrVNlrS9er7Xl7qxwc0ceTHwZxVA=,iv:6hajMcQ1fGdx+KnKG8LsDkRmB9E5FK1Gcq0fVu9vtZA=,tag:YPrTDzeAsP2ALA3k/rnVYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
