apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio
    namespace: default
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:HIrxnBGoJOT3TkxczX8FMIeJlcP656vDsniOGF7nl7r08aTWkLIVpGLvWF4nqpZCgwn28gnvKdyOjqOFFjKY5Gw86K1HeCM1jR3VsNCICdBG1BRNc+p6iCqxJ1Eq+C/3zP4=,iv:cRrPZD4LoRHOKR4vA5Kgt5f1JPuCVN+KUB2I9mPd37g=,tag:HTk9Y41HWtdwpxO3L9yxHg==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:Fy/PdlQf4Bf4,iv:8YNqx50KZ8CZE4Xbbo+TA/OxkTbDMJjgDfnnO4v3lYQ=,tag:DvU3yNbHqH+Au2YYhhhNkw==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:JCn01w==,iv:5xFCR1sIGdEkspjw7Cze9tmzdztidGu5tzOVhAIf7cs=,tag:G+R713+g65rteWT65aryzQ==,type:str]
    JWT_SECRET_KEY: ENC[AES256_GCM,data:GZaNsz4GP5L7K/psaw==,iv:pvowhq/b8jQj5FEVIGml/qb97Wa9miOltl8iM5kmbaE=,tag:kwvgPFBsZXnkp4igXP4kzw==,type:str]
    COMPOSE_PROJECT_NAME: ENC[AES256_GCM,data:lFezTy+Bmwxdm/1c+ft22/tPJvabCAbIRbX90JOvlIHWvofpldLlddV0OJxzFKv4Tny6sNkhOQqhtiE=,iv:VccuQ1L4KwYbasiaRmYF7G75pQvRkaVzS2VcNI+3/w8=,tag:esVeLfDXLtXo/0+OV0E5Gw==,type:str]
    PORT: ENC[AES256_GCM,data:JaD5nQ==,iv:+Du5KLc64rKvXJxowcQz9wFXOyydCvuzRa20qGZszAs=,tag:CFJ2iJf2UWD+N7vc6G6i9w==,type:str]
    ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:RH1qbZDmsjKXFL3DEZfB,iv:z89g8KZYXnXv5IIlbRKG72N+ebLFI7zkznw+9Wx3/to=,tag:1PL4tb86pRQqKEKSEO/pmQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:mBr1YagTCVAZRfWI56hQdEAAdNA1ioIt,iv:2PWulw8phAqkxbBYvzBgWeXorOKyDT21XBDEgUflVDA=,tag:8GMjk9obPYom5b947HIz+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13pchl42neheadfr9vun5h7ky7sdxvg2xywgkxz2vvzwh56fdvuds65e0q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcEJsTDE4UkVtUEFKNWlz
            Z2pScFhDSlJFdmZIa3dmaVBqMzhoWmpQRWg0Cm1vUkpGVUVWWk9yRlZxNHFUd1gr
            bkhpY05oOS9MYXg4eXB6MlRkQkQzUEkKLS0tIFFnc0Z5cFJSSkVwNVZQMC9jbFk0
            VlJQQ2VPVVhNdE5Rd3d0UGpMaDFuaXcKWaC8S0ftk/Zz/d6m/Kbd8qIRxUt6AFUa
            ZAA4W9ZR4ZK8ZhWlVBoV0VpzxRFJvowCQ9NgHKQfLtda6GUspWLa9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-02T17:38:26Z"
    mac: ENC[AES256_GCM,data:iZvHQEdmvKoXvRvrZ5KfBDgAVzpTw4ixXSpBLByHfCB2bbYCx34fBUt+4qtUCV1Z7ZYjrgIWtLDJxUgwaBP/aTkSNhKelp7v/0F6XiL1nuDmIyOhzvQj823QE8LkeHpW/fKMdKbDv4rhK8A39WsOlfuccheZgyuxuFYG14G0vkA=,iv:mjo8Q5pkeZJHtqhPHaBhplFmHP/F/w5uxor74z6NSD4=,tag:AWlWNi+oXktk1rgvMW0jjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
