---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dsmr-reader-postgresql1
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
