---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dsmr-reader-database
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 11.1.29
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    auth:
      database: dsmr-reader
      existingSecret: dsmr-reader-database
      persistence:
        enabled: true
        existingClaim: dsmr-reader-postgresql
# for exposing external
#    primary:
#      service:
#        type: LoadBalancer
#        loadBalancerIP: "192.168.1.13"
