---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-stor
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
