---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app influxdb
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    global:
      nameOverride: *app
    image:
      repository: docker.io/influxdb
      tag: "2.2.0"
    env:
      TZ: "${TIMEZONE}"
    envFrom:
      - secretRef:
          name: *app
    persistence:
      config:
        enabled: true
        existingClaim: influxdb-stor
    service:
      main:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-local-only-access@kubernetescrd"
        hosts:
          - host: "influx.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "influx.${SECRET_DOMAIN}"
            secretName: "influx-tls"
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
