---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app postgres
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 11.1.29
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    global:
      nameOverride: *app
    env:
      TZ: "${TIMEZONE}"
    envFrom:
      - secretRef:
          name: *app
    persistence:
      config:
        enabled: true
        existingClaim: postgres-config-v1
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-local-only-access@kubernetescrd"
        hosts:
          - host: "postgres.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "postgres.${SECRET_DOMAIN}"
            secretName: "postgres-tls"
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
