---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app postgres
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 11.1.29
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    auth:
      database: dsmr-reader
      existingSecret: dsmr-reader
    env:
      TZ: "${TIMEZONE}"
    persistence:
      config:
        enabled: true
        existingClaim: postgres-config-v1
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
