apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: home-automation
stringData:
    POSTGRES-PASSWORD: ENC[AES256_GCM,data:0vfKyFnVXC8LCX/VDk98iVWBrk3da9EXTas=,iv:+A4I1RAnDqyDPKuPwD3FYGa271OfCJnX+2hiDHCB8N8=,tag:Uwk726ETpjON2wu1y20F9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13pchl42neheadfr9vun5h7ky7sdxvg2xywgkxz2vvzwh56fdvuds65e0q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTm0xVVJsUWJqYmxyMVEx
            TUtnQnloVU9RUi9OamZjWHBFc2xlMThqUjI4CksvRngwNlNzazl5U2d4VXRac2JL
            RkdQNHJyN1YvMXJUWXNXclRpYXdYQncKLS0tIGVydTZJRk01ejRDTXVmZGFaV1Ru
            bXhBUGNXNnZGODIxL2R3aG82dVp2dFEKA1dVIPf55StpuvgG2//RklMb+N7q3N8q
            CmO7MXv5wssAHchgH2y1JbFkdHbxj5Fh8VVkrm+u+xcmTZXTAPLS0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-23T18:02:39Z"
    mac: ENC[AES256_GCM,data:nfQrJ+ydjvCcCrp1VpdBuNqUQbFactWecVM9zf6rRXvDRUFFt/RGJ7w8Q6pK+apnXVNNcoPxl1KaoQnr7tGs1jJj3Y53bO9ks7s8e6+ZITFk3+aiVGRPO58BUfGxH4Ct3It6Hr4oz6oxvT66VkGpJtGq9vJmwv0HfHnFcvltvUg=,iv:PUppLGj0Y39Y5QnefM0ewjaCVOVuuZZqdGOiTWc/xcE=,tag:8PnB3qxHmKB2oKAjkqxMoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
