apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emby
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: emby
      version: 3.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/k8s-at-home/emby
      tag: v4.6.1.0
      pullPolicy: IfNotPresent
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 8096
          https:
            enabled: true
            port: 8920
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "emby.${SECRET_PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-v1
      media:
        enabled: true
        type: nfs
        server: "192.168.1.4"
        path: /mnt/media
        mountPath: /media
        readOnly: true
      transcode:
        enabled: true
        type: emptyDir
