apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: sabnzbd
      version: 9.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/k8s-at-home/sabnzbd
      tag: v3.6.0
      pullPolicy: IfNotPresent
    env:
      TZ: "${TIMEZONE}"
      HOST_WHITELIST_ENTRIES: >-
        sabnzbd,
        sabnzbd.media,
        sabnzbd.media.svc,
        sabnzbd.media.svc.cluster,
        sabnzbd.media.svc.cluster.local,
        sabnzbd.${SECRET_DOMAIN}
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "download"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-local-only-access@kubernetescrd"
        hosts:
          - host: "sabnzbd.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "sabnzbd.${SECRET_DOMAIN}"
            secretName: "sabnzbd-tls"
    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config-v1
      media:
        enabled: true
        type: nfs
        server: "192.168.1.4"
        path: /mnt/pool-01/media
        mountPath: /media
        readOnly: false
      incomplete:
        enabled: true
        type: emptyDir
