apiVersion: v1
kind: Secret
metadata:
    name: rsst-to-telegram
    namespace: default
stringData:
    TOKEN: ENC[AES256_GCM,data:4cyAiyNXN9lpPt7WpQApASc7tIsGxz7PJ37WnXHGN6yqLrEyktvomuIrCJT5XA==,iv:OCo0hCq3ryWfaJIMrvnTwz3Mp1AEf/TGhj2D4ZOrmSg=,tag:p7wiaLO8RdyTeEA+DRE08Q==,type:str]
    MANAGER: ENC[AES256_GCM,data:PLVQ15AV7Vg3VQ==,iv:jF0J+7Xvk7ARbxzgPe8NfAC9wULxwvp6hN6/PQOhjjk=,tag:pFuniznZFojog+unWCJgwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13pchl42neheadfr9vun5h7ky7sdxvg2xywgkxz2vvzwh56fdvuds65e0q9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcXdPd0ZnTWtrZTIwUExh
            NWZOMzFFTEpsRXpSNmpCL3ZaNmxsS05Ra3k4CkVyZUsxcXJaOVorWXprWEZqWjRa
            UW8wb0ZpMXV5YTRIWnE0WTROM2tFMDQKLS0tIGNEYlh2K2ZyNDdsSDZMOURTUWpB
            ajVQbTRRSXFROWVNQ0l6SmZOYUhVMkUKAHbpnOGZDTYFFLi1FJGzbeB2Z8xI//4s
            bo75DKvV8JbHVZcVegguw8OqqtKgtW/TjDHDqatle2jXe6yj0J/jbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-19T09:00:36Z"
    mac: ENC[AES256_GCM,data:hu/glsl78QAfmeIHEoxnW4rDpCKma5JAj2kMPmBInA/XYOr7MnV+sugXkIxEbFlKQ2mS4W8MFYGbCbj7xAy2JUpwVZ1nC8RF8RNtLGAN0mP+5rvDDht+Q1fVOV6zpNmWJ3LFQ3D0Lh1G/IyTcDt3rWoyiLSPKoNczijmCJfGaQk=,iv:jm2MLE1vvBJWhU3wRFfUcpl8KtKa70ZcBq5gufnG+oo=,tag:I6G+8fZJThvEQau+YMgxCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
