---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app dsmr-reader
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: dsmr-reader
      version: 6.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: xirixiz/dsmr-reader-docker
      tag: amd64-2022.02.03
    initContainers:
      wait-for-pg:
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command:
          [
            "sh",
            "-c",
            'until nc -vz dsmr-reader-database-postgresql.home-automation 5432; do echo "Waiting for postgresql..."; sleep 3; done;',
          ]
    env:
      TZ: "${TIMEZONE}"
      DJANGO_TIME_ZONE: Europe/Amsterdam
      DJANGO_DATABASE_USER: postgres
      # DJANGO_DATABASE_PASSWORD: set by valuesFrom
      DJANGO_DATABASE_HOST: dsmr-reader-database-postgresql.home-automation
      DJANGO_DATABASE_PORT: "5432"
      DJANGO_DATABASE_NAME: dsmr-reader
      # DSMRREADER_ADMIN_USER: set by valuesFrom
      # DSMRREADER_ADMIN_PASSWORD: set by valuesFrom
    persistence:
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AG4XPUJC-if00-port0
        hostPathType: CharDevice
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-local-only-access@kubernetescrd"
        hosts:
          - host: "dsmr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "dsmr.${SECRET_DOMAIN}"
            secretName: "dsmr-tls"
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
  valuesFrom:
    - kind: Secret
      name: dsmr-reader-database
      valuesKey: postgres-password
      targetPath: env.DJANGO_DATABASE_PASSWORD
      optional: false
    - kind: Secret
      name: dsmr-reader
      valuesKey: dsmr_reader_admin_user
      targetPath: env.DSMRREADER_ADMIN_USER
      optional: false
    - kind: Secret
      name: dsmr-reader
      valuesKey: dsmr_reader_admin_password
      targetPath: env.DSMRREADER_ADMIN_PASSWORD
      optional: false
